--------------------------- MODULE Lifecycle ---------------------------
\* AUTOGENERATED by `dhx regen` from
\* crates/core/src/domain/lifecycle.rs::next — DO NOT EDIT BY HAND.
\* Run `dhx regen` to refresh; `regen --check` fails on drift.
\*
\* Terminal states have no enabled action. Mirrors the FSM table.

EXTENDS TLC

CONSTANTS States, Events
ASSUME States = {"Open", "Frozen", "Closed"}
ASSUME Events = {"Freeze", "Unfreeze", "Close"}

VARIABLE state
vars == << state >>

Init == state = "Open"

Freeze ==
    \/ (state = "Open" /\ state' = "Frozen")

Close ==
    \/ (state = "Open" /\ state' = "Closed")
    \/ (state = "Frozen" /\ state' = "Closed")

Unfreeze ==
    \/ (state = "Frozen" /\ state' = "Open")

Next == Freeze \/ Close \/ Unfreeze

Spec == Init /\ [][Next]_vars

\* INVARIANT: state is always one of the legal values.
TypeInvariant == state \in States

\* INVARIANT: terminal states have no enabled action.
ArchivedTerminal == (state = "Closed" => ~ ENABLED Next)

=============================================================================
