//! Deterministic TLA+ rendering for the lifecycle FSM, split from `fsm.rs` to
//! keep each file within the ≤400 budget dhx enforces on itself (G4).
use crate::fsm::Transition;

/// Render the lifecycle `.tla` from the parsed FSM. The TLC module name MUST
/// equal the filename stem, so it is passed in. Deterministic: identical input
/// always produces byte-identical output.
pub(crate) fn render_tla(
    module: &str,
    source: &str,
    states: &[String],
    events: &[String],
    transitions: &[Transition],
) -> String {
    let set = |xs: &[String]| {
        xs.iter()
            .map(|x| format!("\"{x}\""))
            .collect::<Vec<_>>()
            .join(", ")
    };

    // Events that actually have transitions, in first-appearance order.
    let mut acting_events: Vec<String> = Vec::new();
    for t in transitions {
        if !acting_events.contains(&t.event) {
            acting_events.push(t.event.clone());
        }
    }
    // Terminal states never appear as a transition source.
    let sources: std::collections::BTreeSet<&str> =
        transitions.iter().map(|t| t.source.as_str()).collect();
    let terminal: Vec<&String> = states
        .iter()
        .filter(|s| !sources.contains(s.as_str()))
        .collect();

    let init = states.first().map_or("Active", String::as_str);

    let mut s = String::new();
    let bar = "-".repeat(27);
    s.push_str(&format!("{bar} MODULE {module} {bar}\n"));
    s.push_str("\\* AUTOGENERATED by `dhx regen` from\n");
    s.push_str(&format!("\\* {source} — DO NOT EDIT BY HAND.\n"));
    s.push_str("\\* Run `dhx regen` to refresh; `regen --check` fails on drift.\n");
    s.push_str("\\*\n");
    s.push_str("\\* Terminal states have no enabled action. Mirrors the FSM table.\n\n");
    s.push_str("EXTENDS TLC\n\n");
    s.push_str("CONSTANTS States, Events\n");
    s.push_str(&format!("ASSUME States = {{{}}}\n", set(states)));
    s.push_str(&format!("ASSUME Events = {{{}}}\n\n", set(events)));
    s.push_str("VARIABLE state\n");
    s.push_str("vars == << state >>\n\n");
    s.push_str(&format!("Init == state = \"{init}\"\n\n"));

    for ev in &acting_events {
        s.push_str(&format!("{ev} ==\n"));
        let arms: Vec<&Transition> = transitions.iter().filter(|t| &t.event == ev).collect();
        for t in arms {
            s.push_str(&format!(
                "    \\/ (state = \"{}\" /\\ state' = \"{}\")\n",
                t.source, t.target
            ));
        }
        s.push('\n');
    }

    let next_rhs = acting_events.join(" \\/ ");
    s.push_str(&format!("Next == {next_rhs}\n\n"));
    // Safety-only spec: no fairness conjunct. The project checks no liveness
    // property (the .cfg lists only INVARIANTs), so `WF_vars(Next)` would be
    // dead weight — and a tempting `<>(state = terminal)` liveness PROPERTY is
    // unsound here because the Active⇄Done cycle means weak fairness cannot
    // force the terminal transition. Mirrors the manual ConcurrentApi spec.
    s.push_str("Spec == Init /\\ [][Next]_vars\n\n");
    s.push_str("\\* INVARIANT: state is always one of the legal values.\n");
    s.push_str("TypeInvariant == state \\in States\n\n");
    s.push_str("\\* INVARIANT: terminal states have no enabled action.\n");
    let terminal_guard = if terminal.is_empty() {
        "TRUE".to_owned()
    } else {
        terminal
            .iter()
            .map(|t| format!("(state = \"{t}\" => ~ ENABLED Next)"))
            .collect::<Vec<_>>()
            .join(" /\\ ")
    };
    s.push_str(&format!("ArchivedTerminal == {terminal_guard}\n\n"));
    s.push_str("=============================================================================\n");
    s
}

/// Render `tla/TodoLifecycle.cfg` from the parsed FSM. The `.cfg` independently
/// pins `CONSTANTS States/Events`, so it is a *second* projection of the same
/// source of truth and must be regenerated alongside the `.tla` — otherwise a
/// new state/event in `state.rs` would leave the `.cfg` stale (TLC would then
/// abort on the `ASSUME States = {...}` mismatch, but only under the full-only
/// `tlc` gate). Deterministic: identical input → byte-identical output.
pub(crate) fn render_cfg(states: &[String], events: &[String]) -> String {
    let set = |xs: &[String]| {
        xs.iter()
            .map(|x| format!("\"{x}\""))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let mut s = String::new();
    s.push_str("SPECIFICATION Spec\n");
    s.push_str("INVARIANT  TypeInvariant\n");
    s.push_str("INVARIANT  ArchivedTerminal\n");
    s.push_str(&format!("CONSTANTS  States = {{{}}}\n", set(states)));
    s.push_str(&format!("           Events = {{{}}}\n", set(events)));
    s
}
