--------------------------- MODULE Lifecycle ---------------------------
\* AUTOGENERATED by `dhx regen` from
\* crates/core/src/domain/hold.rs::next — DO NOT EDIT BY HAND.
\* Run `dhx regen` to refresh; `regen --check` fails on drift.
\*
\* Terminal states have no enabled action. Mirrors the FSM table.

EXTENDS TLC

CONSTANTS States, Events
ASSUME States = {"Held", "Confirmed", "Released", "Expired"}
ASSUME Events = {"Confirm", "Release", "Expire"}

VARIABLE state
vars == << state >>

Init == state = "Held"

Confirm ==
    \/ (state = "Held" /\ state' = "Confirmed")

Release ==
    \/ (state = "Held" /\ state' = "Released")

Expire ==
    \/ (state = "Held" /\ state' = "Expired")

Next == Confirm \/ Release \/ Expire

Spec == Init /\ [][Next]_vars

\* INVARIANT: state is always one of the legal values.
TypeInvariant == state \in States

\* INVARIANT: terminal states have no enabled action.
ArchivedTerminal == (state = "Confirmed" => ~ ENABLED Next) /\ (state = "Released" => ~ ENABLED Next) /\ (state = "Expired" => ~ ENABLED Next)

=============================================================================
