--------------------------- MODULE Lifecycle ---------------------------
\* AUTOGENERATED by `dhx regen` from
\* crates/core/src/domain/state.rs::next — DO NOT EDIT BY HAND.
\* Run `dhx regen` to refresh; `regen --check` fails on drift.
\*
\* Terminal states have no enabled action. Mirrors the FSM table.

EXTENDS TLC

CONSTANTS States, Events
ASSUME States = {"Free", "Held", "Confirmed", "Cancelled"}
ASSUME Events = {"Hold", "Confirm", "Release", "Expire", "Cancel"}

VARIABLE state
vars == << state >>

Init == state = "Free"

Hold ==
    \/ (state = "Free" /\ state' = "Held")

Confirm ==
    \/ (state = "Held" /\ state' = "Confirmed")

Release ==
    \/ (state = "Held" /\ state' = "Free")
    \/ (state = "Confirmed" /\ state' = "Free")

Expire ==
    \/ (state = "Held" /\ state' = "Free")

Cancel ==
    \/ (state = "Held" /\ state' = "Cancelled")
    \/ (state = "Confirmed" /\ state' = "Cancelled")

Next == Hold \/ Confirm \/ Release \/ Expire \/ Cancel

Spec == Init /\ [][Next]_vars

\* INVARIANT: state is always one of the legal values.
TypeInvariant == state \in States

\* INVARIANT: terminal states have no enabled action.
ArchivedTerminal == (state = "Cancelled" => ~ ENABLED Next)

=============================================================================
