--------------------------- MODULE Lifecycle ---------------------------
\* AUTOGENERATED by `dhx regen` from
\* crates/core/src/domain/raft/role.rs::next — DO NOT EDIT BY HAND.
\* Run `dhx regen` to refresh; `regen --check` fails on drift.
\*
\* Terminal states have no enabled action. Mirrors the FSM table.

EXTENDS TLC

CONSTANTS States, Events
ASSUME States = {"Follower", "Candidate", "Leader"}
ASSUME Events = {"ElectionTimeout", "MajorityVotes", "HigherTerm", "LeaderAppendEntries"}

VARIABLE state
vars == << state >>

Init == state = "Follower"

ElectionTimeout ==
    \/ (state = "Follower" /\ state' = "Candidate")
    \/ (state = "Candidate" /\ state' = "Candidate")

MajorityVotes ==
    \/ (state = "Candidate" /\ state' = "Leader")

LeaderAppendEntries ==
    \/ (state = "Candidate" /\ state' = "Follower")

HigherTerm ==
    \/ (state = "Candidate" /\ state' = "Follower")
    \/ (state = "Leader" /\ state' = "Follower")

Next == ElectionTimeout \/ MajorityVotes \/ LeaderAppendEntries \/ HigherTerm

Spec == Init /\ [][Next]_vars

\* INVARIANT: state is always one of the legal values.
TypeInvariant == state \in States

\* INVARIANT: terminal states have no enabled action.
ArchivedTerminal == TRUE

=============================================================================
